/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'pale-eucalyptus': '#d2e6bc',
        'pearl-white': '#fafaf5',
        'surface-container': '#eeeee9',
        tertiary: '#725a39',
        'outline-variant': '#cdc6b3',
        'on-error-container': '#93000a',
        'primary-fixed': '#f5e479',
        'secondary-container': '#d2e6bc',
        surface: '#fafaf5',
        'primary-fixed-dim': '#d8c860',
        'surface-tint': '#6a5f00',
        'surface-variant': '#e3e3de',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#576846',
        'surface-container-high': '#e8e8e3',
        'on-error': '#ffffff',
        'on-primary-fixed': '#201c00',
        'inverse-on-surface': '#f1f1ec',
        'on-tertiary-fixed-variant': '#584324',
        'tertiary-container': '#ccae86',
        'surface-container-highest': '#e3e3de',
        'on-tertiary': '#ffffff',
        'on-background': '#1a1c19',
        'on-secondary-fixed': '#111f05',
        'inverse-surface': '#2f312e',
        'on-tertiary-fixed': '#281801',
        'on-secondary-fixed-variant': '#3b4c2c',
        'tertiary-fixed-dim': '#e1c299',
        'tertiary-fixed': '#feddb3',
        'surface-container-low': '#f4f4ef',
        secondary: '#526442',
        'surface-bright': '#fafaf5',
        'on-secondary': '#ffffff',
        outline: '#7c7766',
        'on-primary-container': '#4e4500',
        'on-primary': '#ffffff',
        'inverse-primary': '#d8c860',
        background: '#fafaf5',
        primary: '#6a5f00',
        'on-tertiary-container': '#564122',
        'on-primary-fixed-variant': '#504700',
        'surface-dim': '#dadad5',
        'secondary-fixed': '#d5e9bf',
        'secondary-fixed-dim': '#b9cda4',
        'on-surface-variant': '#4b4738',
        'on-surface': '#1a1c19',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'primary-container': '#c3b44e',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        serif: ['Noto Serif', 'serif'],
        sans: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
